services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lifedata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - lifedata_pg:/var/lib/postgresql/data

volumes:
  lifedata_pg:
